### Numpy Exercises

### Use the following code for the questions below:
 - a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [101]:
# . + tab key for list of options in functions. questionmark at the end provides documentation.
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

1. How many negative numbers are there?

In [170]:
print(a[a < 0])
len(a[a < 0])     

[-2 -1 -6 -7]


4

2. How many positive numbers are there?

In [171]:
print(a[a > 0])
len(a[a > 0])

[ 4 10 12 23  3]


5

3. How many even positive numbers are there?

In [172]:
evens = a % 2 == 0
positives = a > 0
print(a[evens & positives])
len(a[evens & positives])

[ 4 10 12]


3

4. If you were to add 3 to each data point, how many positive numbers would there be?

In [173]:
positives = a_plus_three > 0
a_plus_three = a + 3
print(a_plus_three[positives])
len(a_plus_three[positives])

[ 7 13 15 26  1  2  3  3  3  6]


10

5. If you squared each number, what would the new mean and standard deviation be?

In [13]:
import statistics

In [121]:
a_squared = a ** 2
print(a)
print(a_squared)

[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]
[ 16 100 144 529   4   1   0   0   0  36   9  49]


In [136]:
mean_squared = statistics.mean(a_squared)
std_dev = a_squared.std()
print('The mean and standard deviation of a, respectively, is: {:.2f} and {:.2f}'.format(mean_squared, std_dev))

The mean and standard deviation of a, respectively, is: 74.00 and 144.02


6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set.

In [177]:
a_mean = a.mean()
centering = a - a_mean
print(centering)
print(centering.mean())
print(a_mean)

[  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.]
0.0
3.0


7. Calculate the z-score for each data point. Recall that the z-score is given by:
$Z = \frac{x - \mu}{\sigma}$

In [176]:
a_std_dev = a.std()
(a - a_mean)/a_std_dev

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [31]:
import numpy as np
# Life w/o numpy to life with numpy

#### Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [58]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(a)
print(type(a))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>


#### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [34]:
sum_of_a = sum(a)
sum_of_a

55

#### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [35]:
min_of_a = min(a)
min_of_a

1

#### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [36]:
max_of_a = max(a)
max_of_a

10

#### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [38]:
mean_of_a = statistics.mean(a)
mean_of_a

5.5

#### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

In [41]:
product_of_a = np.prod(a)
product_of_a

3628800

#### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [44]:
squares_of_a = np.power(a, 2)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [59]:
odds_in_a = []
for n in a:
    if n % 2 != 0:
        odds_in_a.append(n)
odds_in_a

[1, 3, 5, 7, 9]

#### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [60]:
evens_in_a = []
for n in a:
    if n % 2 == 0:
        evens_in_a.append(n)
evens_in_a

[2, 4, 6, 8, 10]

#### What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
#### Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]


In [66]:
b = [ [3, 4, 5], [6, 7, 8] ]
b_numpy = np.array([
                    [3, 4, 5,],
                    [6, 7, 8]
                    ])
type(b_numpy)

numpy.ndarray

#### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [68]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b   

33

In [69]:
sum_of_b = b_numpy.sum()
sum_of_b

33

#### Exercise 2 - refactor the following to use numpy. 

In [73]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
min_of_b

3

In [74]:
min_of_b = b_numpy.min()
min_of_b

3

#### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

In [75]:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b

8

In [76]:
max_of_b = b_numpy.max()
max_of_b

8

#### Exercise 4 - refactor the following using numpy to find the mean of b

In [78]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b

5.5

In [79]:
mean_of_b = b_numpy.mean()
mean_of_b

5.5

#### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

In [81]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
product_of_b

20160

In [82]:
product_of_b = np.prod(b_numpy)
product_of_b

20160

#### Exercise 6 - refactor the following to use numpy to find the list of squares

In [83]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
squares_of_b

[9, 16, 25, 36, 49, 64]

In [87]:
squares_of_b = np.power(b_numpy, 2)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

#### Exercise 7 - refactor using numpy to determine the odds_in_b

In [88]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

In [89]:
odds_in_b = (b_numpy[b_numpy % 2 == 1])
odds_in_b

array([3, 5, 7])

#### Exercise 8 - refactor the following to use numpy to filter only the even numbers

In [90]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

In [91]:
evens_in_b = (b_numpy[b_numpy % 2 != 1])
evens_in_b

array([4, 6, 8])

#### Exercise 9 - print out the shape of the array b.

In [95]:
b_numpy.shape

(2, 3)

#### Exercise 10 - transpose the array b.

In [96]:
np.transpose(b_numpy)

array([[3, 6],
       [4, 7],
       [5, 8]])

#### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [178]:
b_numpy.flatten()

array([3, 4, 5, 6, 7, 8])

#### Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [99]:
b_numpy.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

#### Setup 3

c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

#### HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy 
#### array methods.

In [127]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
c_numpy = np.array(c)
type(c_numpy)

numpy.ndarray

#### Exercise 1 - Find the min, max, sum, and product of c.

In [134]:
print(c_numpy.min())
print(c_numpy.max())
print(c_numpy.sum())
print(np.prod(c_numpy))

1
9
45
362880


#### Exercise 2 - Determine the standard deviation of c.

In [135]:
c_numpy.std()

2.581988897471611

#### Exercise 3 - Determine the variance of c.

In [141]:
c_numpy.var()

6.666666666666667

#### Exercise 4 - Print out the shape of the array c.

In [140]:
print(c_numpy.shape)

(3, 3)


#### Exercise 5 - Transpose c and print out transposed result.

In [145]:
np.transpose(c_numpy)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### Exercise 6 - Get the dot product of the array c with c. 

In [147]:
np.dot(c_numpy, c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

#### Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261.

In [155]:
np.sum(c_numpy * np.transpose(c_numpy))

261

#### Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

In [153]:
np.prod(c_numpy * np.transpose(c_numpy))

131681894400

#### Setup 4

d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [156]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d_numpy = np.array(d)
type(d_numpy)

numpy.ndarray

#### Exercise 1 - Find the sine of all the numbers in d

In [157]:
np.sin(d_numpy)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

#### Exercise 2 - Find the cosine of all the numbers in d

In [158]:
np.cos(d_numpy)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

#### Exercise 3 - Find the tangent of all the numbers in d

In [159]:
np.tan(d_numpy)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

#### Exercise 4 - Find all the negative numbers in d

In [160]:
d_numpy[d_numpy < 0]

array([-90, -30, -45, -45])

#### Exercise 5 - Find all the positive numbers in d

In [161]:
d_numpy[d_numpy > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

#### Exercise 6 - Return an array of only the unique numbers in d.

In [163]:
np.unique(d_numpy)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

#### Exercise 7 - Determine how many unique numbers there are in d.

In [179]:
print(np.unique(d_numpy))
len(np.unique(d_numpy))

[-90 -45 -30   0  30  45  60  90 120 180 270]


11

#### Exercise 8 - Print out the shape of d.

In [165]:
d_numpy.shape

(3, 6)

#### Exercise 9 - Transpose and then print out the shape of d.

In [167]:
np.transpose(d_numpy).shape

(6, 3)

####  Exercise 10 - Reshape d into an array of 9 x 2

In [168]:
d_numpy.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])